version: '3.8'

services:

  # web entry point
  web:
    container_name: web
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    ports:
      - "3060:80"
    networks:
      - tsc_api

  api:
    container_name: api
    build: 
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - ./api:/app
      # - /app/node_modules
    env_file:
      - .env
    networks:
      - tsc_api

  # database - postgres:10
  data_store:
    container_name: data_store
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_DB: "${DB_DATABASE}"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5500:5432"
    networks:
      - tsc_api

  # mailer 
  mailhog:
    container_name: mailer
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"


volumes:
  postgres_data:
networks:
  tsc_api:
    driver: bridge